config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'tokens#new'

  resources :tokens, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def new; end

  def create
    respond_to do |format|
      format.turbo_stream do
        @token = calculate_token

        render turbo_stream: turbo_stream.replace(
          :result,
          partial: 'tokens/create'
        )
      end
    end
  end

  private

  def calculate_token
    Base64.strict_encode64(
      OpenSSL::HMAC.digest 'sha256', params[:key], params[:body]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HmacAuth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex justify-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tokens/_create.html.erb
<div id='result'>
  <% if @token.present? %>
    <h2 class='text-blue-500 bold mt-5'>Here's your auth token:</h2>
    <p class='ml-5'><%= @token %></p>
  <% end %>
</div>

app/views/tokens/new.html.erb
<div>
  <h1 class="font-bold text-4xl text-blue-500 mb-5">HMAC-SHA256 Encryption</h1>

  <%= form_with url: tokens_path, local: true do |form| %>
    <%= form.label :key, 'Secret Key:' %>
    <%= form.text_field :key, class: 'block mb-5 w-144' %>
    <%= form.label :body, 'Body:' %>
    <%= form.text_area :body, class: 'w-144 h-48 block' %>
    <%= form.submit 'Submit', class: 'mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded', data: { disable_with: false } %>
  <% end %>

  <%= render partial: 'tokens/create' %>
</div>